### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by apixandru**
the chrome webstore changed the href

### CODE REVIEW

**Comment by PF4Public** [comment]
Please explain your intentions with this change. What was broken and how did you fix it.

**Comment by MrChocolatine** [comment]
Can we move forward with this PR?

The proposed changes work, see: https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/174#issuecomment-2218043171

**Comment by PF4Public** [comment]
> Can we move forward with this PR?

Yes, the question is up above… unanswered.

**Comment by MrChocolatine** [comment]
> Please explain your intentions with this change. What was broken and how did you fix it.

Here you go:

### Issue

The bookmarklet currently suggested in the FAQ is outdated and does not work anymore.
When using it, nothing happens, the prompt to install extensions is not displayed anymore.

The `href` for targeting the right element appear to have changed:
```html
<a href="./detail/oboonakemofpalcgghocfoadofidjkkk">...</a>
```

### Fix

This PR updates the CSS selector that allows to extract extensions' ID from their Chrome Web Store page.

---

PS: Why is PR blocked just for that. While, when looking at other PRs that were merged, their description was as brief as this one...

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
fixes extension downloads not working, so I guess this is good

**Pull request merged**
