### PR TITLE
Another option to install extensions

### PR DESCRIPTION
**Pull request by fabianski7**
I wasn't able to install extensions in any way listed in the FAQ, so I had to install that way.

### CODE REVIEW

**Comment by Eloston** [comment]
I'm assuming you're on Windows. On Windows, you should be able to do the same thing with 7-zip without needing to use a website. Maybe we should reference the Windows bug report instead?

**Comment by fabianski7** [comment]
No. I'm on linux, with kde plasma. 
The ark (the utility to compression/decompression from DE) is not compatible with this file extension (.crx).

**Comment by Eloston** [comment]
I'm running Debian buster, and I can use Chromium Web Store (linked from the FAQ) to install extensions just fine. Which Linux variant are you using?

**Comment by fabianski7** [comment]
Arch linux. 
The drag and drop isn't working.

FAQ: "NOTE: There are certain circumstances where this method fails on KDE Plasma."

**Comment by Eloston** [comment]
> The drag and drop isn't working.

Yeah it isn't working on any Linux version right now. You can still install extensions using Chromium Web Store (which needs to be installed via Developer tools)

**Comment by fabianski7** [comment]
Yeah. That's right. That's why I'd like to add this alternative method. Because none of the current ones worked. 
Forget it.

**Pull request closed without merging**
